@startuml Схема сотрудника FinanceTrack
skinparam conditionStyle diamond
skinparam linetype ortho

title Добавление сотрудника

(*) --> "начало"
--> "вход в систему" as login

if "Пользователь ==\n'Руководитель'?" then
  -->[да] "Выбор пункта 'Добавить\nсотрудника'"
  --> "Ввод данных о новом\nсотруднике"
  --> "конец"
  --> (*)
else
  -->[нет] "вывод ошибки 'Доступ\nзапрещен'"
  --> login
  note on link
    назад к авторизации
  end note
endif

@endum